### ISSUE TITLE
Remove flat_return api feature.

### ISSUE THREAD

**Issue by andersroos** [makerspace/makeradmin#111]
Some api endpoints returned flattened data, fix these endpoints to not do it (and all usages), then remove the flat_return api feature.

**Comment by emanuelen5** [comment]
Is this issue relevant anymore? It sounds like a "code style" issue, rather than a risk / problem with implementation.

**Comment by andersroos** [comment]
Ja, finns som sagt massor med andra saker att förbättra också.
