### ISSUE TITLE
Change api expand to put result into sub object.

### ISSUE THREAD

**Issue by andersroos** [makerspace/makeradmin#116]
Currently expand objects in api calls are added flattened, add objects as sub objects instead.

**Comment by DevJohan** [comment]
Is this the same issue as #111 only worded differently?

**Comment by andersroos** [comment]
No, totally different thing. Flatten in #111 puts the items under data directly in the response dict.

**Comment by emanuelen5** [comment]
Stale?

**Comment by andersroos** [comment]
Ja, finns massor med förbättringspotential, vet inte varför det här är speciellt.
