### ISSUE TITLE
Improve (admin) error handling

### ISSUE THREAD

**Issue by andersroos** [makerspace/makeradmin#117]
Problems with gateway code and server responses in general:
- In the (admin) client we handle all errors from server in the same way, ideally we should have a common way to handle expected errors (for example problems related to user input). Problem is that we reject on all non 200, non 401 and non 403 and display a generic error.
- We accept on 401 and 403 which means that there is no nice distinction for this in accept.
- Server code have a status field that could possibly be used, but it only reflects the http status and is not used that much in the client.
- Only display latest error message on client (admin, maybe member).

**Comment by emanuelen5** [comment]
Stale issue
