### ISSUE TITLE
Add editing of mempership spans in admin GUI (and removing backbone dep from membership tab)

### ISSUE THREAD

**Issue by andersroos** [makerspace/makeradmin#18]

**Comment by DevJohan** [comment]
Tänker du göra redigering av medlemsperioder eller kan jag titta på det?

**Comment by andersroos** [comment]
Ja, det tänker jag, som en del av den här. Så det beror lite på hur bråttom du har.

**Comment by DevJohan** [comment]
Det vore bra att ha funktionaliteten att lägga till spans i GUI på plats innan man migrerar nycklar på produktionsservern.

**Comment by andersroos** [comment]
Tycker inte vi ska vänta på det oavsett om vi väntar på den här issuen eller om du gör en quick-fix. Vi kan ju deploya igen om två dagar och sen en gång till om 5 dagar. Det här med att vänta veckor är ju ganska skadligt.

**Comment by DevJohan** [comment]
Håller med. Jag kommer dessutom vara med på kommande nyckelutlämningar så det kommer förmodligen inte vara ett problem.

**Comment by andersroos** [comment]
Mål:
- Ersätta backbone med egen enkel funktionalitet (vi använder väldigt lite av backbone).
- Renodla generiska react-komponenter.
- Inte låtsas att icke generiska react-komponenter är det.
- Förenkla filstruktur.
- Ta bort onödig/ofärdng funktionalitet.
