### ISSUE TITLE
See a list of all members pending to have their membership activated or lab time extended

### ISSUE THREAD

**Issue by nitro2k01** [makerspace/makeradmin#213]
Feature request: A page where all members who have purchased a starter pack (or just a föreningsmedlemskap) but has not activated their membership/signed the contract.

The same, but for pending key extensions. (Although this may be less relevant after the switch to Accessy.)

This would give a quick overview to inform the need for key handout events or "nightly" key extensions.

**Comment by emanuelen5** [comment]
We came to the conclusion that this is not prioritized since we will be soon switching to the Accessy system.

**Comment by emanuelen5** [comment]
This is not relevant anymore
