### ISSUE TITLE
SMS verification

### ISSUE THREAD

**Issue by emanuelen5** [makerspace/makeradmin#215]
We need to verify the phone number to integrate with Accessy (access control system with phone).

### Frontend flow
  1. Press change number
  2. Send verification SMS with code (save in database)
  3. Ask for SMS code
  4. Verify SMS code
  5. SMS code expires after 5 minutes

### Database table
  * Phone number
  * Member ID
  * Code
  * Completed
  * Timestamp

# SMS services

## intime.nu 
* Swedish company
* 125 kr/mån
* 0.59 kr/sms

```bash
curl -X POST -k -i 'https://sms.intime.nu/api/1.0/message/create.ashx?user=${USERNAME}&hash=${APIKEY}' --data \
 '<?xml version="1.0" encoding="iso88591"?>
<message>
<flash>0</flash>
<multisms>0</multisms>
<sendertitle>MAKERSPACE</sendertitle>
<body>Här kommer din tvåstegsverifieringskod ${CODE}</body>
<checknix>0</checknix>
<anonymize>1</anonymize>
<recipients>
	<recipient>+46701234567</recipient>
</recipients>
</message>'
```

## rule.se
* Kostnad per användare.
* 200kr/mån för 200 användare, 600kr/mån för 2500 användare.

## smsglobal.com
* Ingen startavgift.
* 1-4000 sms => 0.72 kr/sms.
* Går inte att registrera sig på deras sida för jag får ingen verifieringskod på SMS...

## hellosms.se
* Swedish company
* 39 kr/mån
* 0.40 kr/sms
* Forward SMS from email. **No API**

## 46elk
* Swedish Servers
* 0 kr/mån
* 0.39 kr/sms

```python
import requests

response = requests.post(
  'https://api.46elks.com/a1/sms',
  auth = (API_USERNAME, API_PASSWORD),
  data = {
    'from': 'PythonElk',
    'to': '+46700000000',
    'message': "It's cold outside, bring a sweater!"
  }
)
print(response.text)
```

## twilio
* $ 0.0550 /sms

```bash
curl -XPOST https://api.twilio.com/2010-04-01/Accounts/ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Messages \\
    -d "Body=All%20in%20the%20game%2C%20yo" \\
    -d "To=%2B14108675310" \\
    -d "From=%2B15005550006" \\
    -u 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:your_auth_token'
```

**Comment by emanuelen5** [comment]
Using the SMS service intime.nu works using the following cURL:

```bash
curl -X POST -k -i 'https://sms.intime.nu/api/1.0/message/create.ashx?user=${USERNAME}&hash=${APIKEY}' --data \
 '<?xml version="1.0" encoding="iso88591"?>
<message>
<flash>0</flash>
<multisms>0</multisms>
<sendertitle>MAKERSPACE</sendertitle>
<body>Här kommer din tvåstegsverifieringskod ${CODE}</body>
<checknix>0</checknix>
<anonymize>1</anonymize>
<recipients>
	<recipient>+46701234567</recipient>
</recipients>
</message>'
```

**Comment by emanuelen5** [comment]
Prismodell

# rule.se
* Kostnad per användare.
* 200kr/mån för 200 användare, 600kr/mån för 2500 användare.


# smsglobal.com
* Ingen startavgift.
* 1-4000 + 0.72 kr/sms.


# hellosms.se
* 39 kr/mån
* 0.60 kr/sms

**Comment by andersroos** [comment]
Backend now done, except integration to sms service and some additional test.

**Comment by jine** [comment]
https://www.twilio.com/ har vi spons för ideella förening. använder det själv, tror fan vi har ett konto där redan också.
(typ par hundra dollar i spons, f.ö. - räcker till MÅNGA sms)

**Comment by emanuelen5** [comment]
Good additions, I'll add them to the list

**Comment by emanuelen5** [comment]
BTW, found some nice documentation on the number format: https://46elks.com/kb/e164
