### ISSUE TITLE
Accessy: Remove old junk

### ISSUE THREAD

**Issue by andersroos** [makerspace/makeradmin#233]
Remove all old junk no longer needed when accessy is up and running:
* [ ] rfid tags
* [x] multiacess program
* [ ] etc...
* [ ] etc...
* [ ] etc..

**Comment by emanuelen5** [comment]
Please refine TODOs...

**Comment by emanuelen5** [comment]
Is this done? I see not rush in removing RFID tags. We can do that later if necessary.

**Comment by amrsoll** [comment]
I would be interested in an RFID or NFC tag system. What PRs are relating to this issue? I would like to create a wrapper around a generic access permission system that can interface with a lock system such as Accessy or other NFC/RFID tag systems.
See comments in #387

**Comment by emanuelen5** [comment]
Agreed, let's consider this done
