### ISSUE TITLE
Improve accounting support

### ISSUE THREAD

**Issue by agehall** [makerspace/makeradmin#295]
There is currently a script that can extract all transactions for a whole year-to-date and produce an SIE file that can then be imported into the book keeping software. This script produces one transaction in the book keeping software per transaction made in the web shop which means that there will be a LOT of transactions entered into the books which makes the book keeping a bit more difficult as it means all detailed reports will blow up in size and be difficult to use.

To improve this, I would like to see a function in Makeradmin that allows admins to pull sales reports on a weekly or monthly basis and creates a single book keeping record for all makeradmin transactions during the period.

The output report can either be in plain text/HTML that can be used to create a manual entry into the book keeping software or in the form of an SIE file. The important thing is that the output should represent a single record to be entered into the book keeping software instead of one per web shop transaction.

The source of truth here should be Makeradmin records but bonus points if we can still verify all transactions against Stripe when the report is generated.

For those not familiar with book keeping, different goods (e.g. drills vs vinyl) should be reported on different accounts. These accounts are 4 digits, ranging from 1000-9999. We should allow for the account to be specified on each item in the web shop. Since all records must balance, there must also be a “target account” which can be a configuration setting in the Makeradmin config files - it will rarely change if ever.

Note: The report does NOT have to handle refunds. These are handled manually.

**Comment by emanuelen5** [comment]
Implemented in #420
