### ISSUE TITLE
Usability: Membership overview

### ISSUE THREAD

**Issue by andersroos** [makerspace/makeradmin#30]
To make it simpler to do nyckelutlämning and other common tasks, the most common membership fields should be editable on the overview page. Maybe start with the following:

Edit: Name, Email, Personnummer, RFID tag, Lab membership, Phone number
Show: Unresolved orders, Membership, Address, Group memberships.

**Comment by SimonTemplate** [comment]
Two main areas to improve upon:
- Process oriented dialog for amending member, adding fob no and socsec no and also checking email.
- Sync fobs from within makeradmin multi_access_sync, thus no need to start and logon to MultiAccess main program.

**Comment by emanuelen5** [comment]
@InMyOrbit has started this in the branch 30-member-overview
