### ISSUE TITLE
Optionally mock Accessy requests

### ISSUE THREAD

**Issue by emanuelen5** [makerspace/makeradmin#306]
Running Makeradmin without a valid Accessy token results in lots of errors. Add a mocked mode of Accessy to make it easier to use during development.

**Comment by emanuelen5** [comment]
Fixed in 8f41f2e68c604593d147cf035d4aaba54baa5e24

**Comment by BerglundDaniel** [comment]
There is some issue that which prevents running without the accessy

**Comment by BerglundDaniel** [comment]
Fixed in #328
