### ISSUE TITLE
Make access groups more granular

### ISSUE THREAD

**Issue by BerglundDaniel** [makerspace/makeradmin#309]
The access permission groups could be more granular. Instead of having only special access we should split it into the space itself, the corridor and Nobel

**Comment by Cederb** [comment]
Wasn't stuff like this the intention of the "Grupper" functionality, which has never been used a lot, so you could create a group called "Nobelaccess" and assign members of that group access to Nobel?

**Comment by BerglundDaniel** [comment]
Noticed that this is a duplicate of #293
