### ISSUE TITLE
[Questions] A system overview

### ISSUE THREAD

**Issue by amrsoll** [makerspace/makeradmin#314]
Hi,

I am part of a smaller makerspace in Odense, Denmark.

I would love to know how much work there would be in trying to 'white label' the repo so we can both adopt and contribute to this platform :)

I am happy to see that the docker composes 'just work' so that's cool. We use stripe as well, although with a duct-taped backend so I'm looking forward to move to something robust :smile:  Are there any requirements for external resources such as Stripe that I should be aware of (structring the memberships etc...) ?

I know this is not the ideal format to reach out, but I thought it was better than the info@ mail.

Would it be possible to discuss? I would love to help out. I would first concentrate on internationalisation and translations (#310) :denmark: :fr: :gb: :smile:

Also, I understand that the site is very tailor-made for your usage, but our needs are literally a subset of what you have made ^^

Lastly, I don't see a license on the code so... Is there any? :)

**Comment by HalfVoxel** [comment]
Hi

Cool!

The system is pretty flexible and can definitely support another makerspace. The parts that are the hardest to switch out are probably the ones related to our membership system. Stockholm Makerspace has one yearly membership fee and one monthly membership fee (for actually getting access to the space).
Changing this to something else may be a bit more involved.

In #312 there's also a basic localization system included for the member portal, so adding danish and even customizing all messages in the frontend for your makerspace should be possible (though some things do leak from the backend, and not all the frontend is localized yet, but the architecture is in place).

There's no license yet, I guess. But if anything, it would probably be MIT.

**Comment by HalfVoxel** [comment]
>  Are there any requirements for external resources such as Stripe that I should be aware of (structring the memberships etc...) ?

Currently the stripe configuration is minimal. No products need to be defined in stripe.
For the subscriptions instruduced in #312, some configuration is necessary. See https://github.com/makerspace/makeradmin/blob/19394898b964a18596b9cb842caea99136ea66c7/README.md#setting-up-stripe-subscription-products

**Comment by amrsoll** [comment]
Thank you for the pointers! :D

fiuuu that PR is gurthy, perhaps I should base my testing on that PR or wait for it to be merged? :)

**Comment by HalfVoxel** [comment]
It will likely be merged soon, so basing your testing on that PR seems reasonable.
