### ISSUE TITLE
Products categories without any visible items are shown

### ISSUE THREAD

**Issue by emanuelen5** [makerspace/makeradmin#316]
## Example
The subscriptions category has no visible items, but it is still showing in the left pane: <br/>
![image](https://github.com/makerspace/makeradmin/assets/7572427/6cb3d713-b4d6-4f69-9c25-c1655b3c8a2b)

## Expected behavior
If all of the items of a product category are hidden, then the category should be hidden as well. It's confusing if it's showing, especially since clicking the category takes the user to the top of the page.

**Comment by HalfVoxel** [comment]
Fixed in 51f5d925
