### ISSUE TITLE
Generate subscription types from Stripe products (beta site)

### ISSUE THREAD

**Issue by amrsoll** [makerspace/makeradmin#325]
I found out that the membership page `http://localhost:8011/member/` will not load properly without these additional subscriptions on Stripe:

- `access_starter_pack`
- `single_membership_year`
- `single_labaccess_month`

They are required according to https://github.com/makerspace/makeradmin/blob/master/public/ts/payment_common.tsx#L405 

Given that their price is already pulled from Stripe, it would be nice if All of these products would be generated entirely from a list of _products_ , their _price_ and associated metadata from Stripe? This way, Stripe becomes the source of truth for anything subscription related.

**Example**
- The `special_product_id` could use  the stripe product id `prod_xxxxxxxxxxxxxx`
- The `display_order` could be passed as a product metadata.

I was able to bypass that problem when setting  `const in_beta_group = false;`

**Comment by amrsoll** [comment]
Ah, I still had a problem rendering `/shop/register2` without those products

**Comment by HalfVoxel** [comment]
It's a tough issue. In makeradmin we add a bunch of data that cannot easily be added to stripe products. And stripe currently has some information that cannot be represented in makeradmin (especially subscription configuration).

Ideally, I think, makeradmin should be the source of truth for ALL products. So it would automatically create the subscriptions on stripe unless they already existed. However, I didn't really have the energy to implement all those changes when I wrote the subscription backend, so it uses stripe as the source of truth for subscriptions instead.

You probably have a different setup for your membership. You can edit which plans you have here: https://github.com/makerspace/makeradmin/blob/543d9d6e782e4e30f10c979d46a97ee4203efb14/public/ts/register2.tsx#L497
Though, the membership page currently assumes a few things.

**Comment by amrsoll** [comment]
I am somewhat more inclined to setup stuff in Stripe instead of extending the interface of makeradmin to give those possibilities.

Is that how you manage other products you are selling on your shop? That backend updates stripe configurations?

**Comment by amrsoll** [comment]
> You can edit which plans you have here

There actually multiple places I would have to modify the available memberships, which is why I think ideally they would be configured in one place, either Stripe, a config file or in the db. I am biased towards having it handled by stripe to reduce complexity.

**Comment by HalfVoxel** [comment]
> I am somewhat more inclined to setup stuff in Stripe instead of extending the interface of makeradmin to give those possibilities.

Stripe has some limitations, like you cannot set the category of a product, and stuff like that.
Sure. It's possible to use metadata for this, but it will give you a much worse editing experience.

Currently, products are not even represented on stripe, except for subscriptions. Instead, we just charge members whatever makeradmin says it should cost. This could definitely be improved, though.

Personally, I am not a huge fan of making stripe be the product source of truth, because it ties the backend even more to using stripe. If we at some point in the future want to change payment provider, this would be much harder due to the lock-in effect.

**Comment by amrsoll** [comment]
You raise some fair points, I'll avoid making the code more dependent on Stripe.

**Comment by HalfVoxel** [comment]
Using a config file or similar would definitely be nicer than the current setup.

The backend doesn't really care about how the membership is setup. The only things it cares about is that there are two membership types (regular membership and labaccess). labaccess gives someone access to the space.
There are also some data-driven validation filters for the membership products. These validate, for example, that you cannot start a subscription if one is already started etc. But this is stored mostly in the database.

The frontend, on the other hand, has a large part of the membership setup hardcoded at the moment.
Breaking this out to a config file is probably a bit of work, but it's doable.

Products should ideally continue to be stored in the database, not in a config file.

**Comment by BerglundDaniel** [comment]
The stripe coupons for discounts should probably stored in the database to somehow
