### ISSUE TITLE
Going to second page of send emails page on a member does not work.

### ISSUE THREAD

**Issue by HalfVoxel** [makerspace/makeradmin#357]
It just shows an infinite spinning icon.

To reproduce:
* Go to a member who has more than one page of messages
* Press any page number other than 1.
* Watch it not work

![bild](https://github.com/makerspace/makeradmin/assets/1144597/0d7835a4-e50d-48ff-9899-7f21cb0a443c)

**Comment by BerglundDaniel** [comment]
Fixed in #438
