### ISSUE TITLE
`pending_actions_query` will return gift purchases

### ISSUE THREAD

**Issue by HalfVoxel** [makerspace/makeradmin#369]
If someone purchases a gift (i.e. transaction with member_id = None) which has a product that also contains product actions, then the `pending_actions_query` will return this transaction, and may try to ship it, resulting in an exception.

@Kotik112

**Comment by Kotik112** [comment]
Added a PR that I think should solve the issue. Please provide feedback.
https://github.com/makerspace/makeradmin/pull/371
