### ISSUE TITLE
Python 3.12 update, datetime.utcnow() deprecation

### ISSUE THREAD

**Issue by BerglundDaniel** [makerspace/makeradmin#508]
It seems that Python 3.12 will work mostly directly for us. The only thing we need to update is that datetime.datetime.utcnow() has warnings about being deprecated

**Comment by emanuelen5** [comment]
@coderabbitai Do you have any suggestions how to fix the issue? And where in the code do we use `utcnow`?

**Comment by emanuelen5** [comment]
Fixed by #555
