### ISSUE TITLE
Add proper documentation site

### ISSUE THREAD

**Issue by emanuelen5** [makerspace/makeradmin#545]
It would be useful if we had documentation separate from the README.
This would enable us to add more example images, and guide on how to _use_ the admin part / how the register flow looks like. And this would also make it possible to keep the documentation more structured (multi-page and formatted).

The README should then ideally only be an overview of what Makeradmin does, and how to get started. It's the first thing someone sees when they find our repo, so it should more or less just show what Makeradmin can offer, and a quick overview of the documentation.

- [ ] Add the skeleton code for building documentation
- [x] Add/point a domain to the docs
- [ ] Host it (using Github pages?)

At a later point (PR) we can add the documentation itself.

**Comment by Lescurel** [comment]
I've looked at [MkDocs](https://www.mkdocs.org/), it looks really straightforward to use, and it's also using python, so we don't introduce one more technology into the stack. 

For hosting, we can use [Github Pages](https://www.mkdocs.org/), or [Read The Docs](https://about.readthedocs.com/) also has a free plan for Open Source projects.
