### ISSUE TITLE
Show pending spans on admin view of a member

### ISSUE THREAD

**Issue by BerglundDaniel** [makerspace/makeradmin#589]
It would be nice if pending spans were also shown on the "Perioder" tab when viewing a member in the admin page. Ideally also have buttons to create and delete spans there

**Comment by emanuelen5** [comment]
Sounds like a noop now that we have instant labaccess? Also, I think that
is already the case on both the "perioder" page and the key handout page.

**Comment by emanuelen5** [comment]
It already exists:

![image](https://github.com/user-attachments/assets/b37be6dd-339c-4d17-913e-156a11fcbaf0)
