### ISSUE TITLE
Replace hard coded reference by product name

### ISSUE THREAD

**Issue by DevJohan** [makerspace/makeradmin#69]
Need better solution for generating statistics on laser usage data

https://github.com/makerspace/makeradmin/blob/3de505bea680389551845838e145b9309b86341a/backend/src/maker_statistics.py#L72

**Comment by andersroos** [comment]
This could be good when linking. Any other benefit except for when doing manual queries for statistics?

**Comment by emanuelen5** [comment]
I don't think this is relevant any more
