### ISSUE TITLE
Send differently worded welcome email if registration payment fails

### ISSUE THREAD

**Issue by DevJohan** [makerspace/makeradmin#97]
Send an email that welcomes the new user and informs them that their purchase om membership failed. Ask them to login and complete the purchase of membership in the shop.

This is one way of handling failed registration. Perhaps another, better, way can be implemented later.

**Comment by emanuelen5** [comment]
This is related to both #114 and #139

**Comment by emanuelen5** [comment]
Beslut att det är bättre att tvinga användaren att registrera sig och logga in först för att kunna köpa medlemskap. På så sätt undviker vi att folk registrerar fel epostadress (vilket är relativt vanligt).
